class ErrorCodes:
    # Centrales
    CENTRALE_NOT_FOUND = "CENTRALE_NOT_FOUND"
    CENTRALE_ALREADY_EXISTS = "CENTRALE_ALREADY_EXISTS"

    # Poissons
    POISSON_NOT_FOUND = "POISSON_NOT_FOUND"
    POISSON_ALREADY_EXISTS = "POISSON_ALREADY_EXISTS"

    NON_POISSON_NOT_FOUND = "NON_POISSON_NOT_FOUND"
    NON_POISSON_ALREADY_EXISTS = "NON_POISSON_ALREADY_EXISTS"

    ECHANTILLONNAGE_NOT_FOUND = "ECHANTILLONNAGE_NOT_FOUND"
    ECHANTILLONNAGE_INVALID_RELATIONS = "ECHANTILLONNAGE_INVALID_RELATIONS"

    INVENTAIRE_INVALID_SPECIES = "INVENTAIRE_INVALID_SPECIES"
    INVENTAIRE_UNEXPECTED_ERROR = "INVENTAIRE_UNEXPECTED_ERROR"
    INVENTAIRE_NOT_FOUND = "INVENTAIRE_NOT_FOUND"
    INVENTAIRE_INVALID_RELATIONS = "INVENTAIRE_INVALID_RELATIONS"
    INVENTAIRE_ALREADY_EXISTS = "INVENTAIRE_ALREADY_EXISTS"

    QUERY_BUILDER_INVALID_ROOT = "QUERY_BUILDER_INVALID_ROOT"
    QUERY_BUILDER_INVALID_RELATION = "QUERY_BUILDER_INVALID_RELATION"
    QUERY_BUILDER_INVALID_FIELD = "QUERY_BUILDER_INVALID_FIELD"
    QUERY_BUILDER_INVALID_OPERATOR = "QUERY_BUILDER_INVALID_OPERATOR"
    QUERY_BUILDER_INVALID_FILTER = "QUERY_BUILDER_INVALID_FILTER"
    QUERY_BUILDER_INVALID_LOGIC = "QUERY_BUILDER_INVALID_LOGIC"
    QUERY_BUILDER_INVALID_ORDER_BY = "QUERY_BUILDER_INVALID_ORDER_BY"

    # Generic
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"

    APP_USER_NOT_FOUND = "APP_USER_NOT_FOUND"
    APP_USER_ALREADY_EXISTS = "APP_USER_ALREADY_EXISTS"
    APP_USER_INVALID_ROLE = "APP_USER_INVALID_ROLE"
    APP_USER_INACTIVE = "APP_USER_INACTIVE"