# Generated by Django 5.0.3 on 2026-03-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="echantillonnage",
            name="date_echantillonnage",
            field=models.CharField(
                blank=True, db_column="Date_d_echantillonnage", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="nonpoissons",
            name="guilde_trophique",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CAR", "Espèce consommant des invertébrés et des poissons"),
                    ("HERB", "Espèce consommant des algues et des végétaux supérieurs"),
                    (
                        "INV",
                        "Espèce consommant des invertébrés (larves, mollusques, crustacés, …)",
                    ),
                    (
                        "OMN",
                        "Espèce consommant des algues, des végétaux, des invéterbrés et/ou des poissons",
                    ),
                    ("PISC", "Espèce consommant des poissons"),
                    ("PLC", "Espèce consommant du zooplancton"),
                    ("NA", "NA"),
                    ("Autre", "Autre"),
                ],
                db_column="Guilde_trophique",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="poissons",
            name="guilde_trophique",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CAR", "Espèce consommant des invertébrés et des poissons"),
                    ("HERB", "Espèce consommant des algues et des végétaux supérieurs"),
                    (
                        "INV",
                        "Espèce consommant des invertébrés (larves, mollusques, crustacés, …)",
                    ),
                    (
                        "OMN",
                        "Espèce consommant des algues, des végétaux, des invéterbrés et/ou des poissons",
                    ),
                    ("PISC", "Espèce consommant des poissons"),
                    ("PLC", "Espèce consommant du zooplancton"),
                    ("NA", "NA"),
                    ("Autre", "Autre"),
                ],
                db_column="Guilde_trophique",
                max_length=30,
            ),
        ),
    ]
