# Generated by Django 5.0.3 on 2026-03-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_echantillonnage_adultes_pct_o_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "oidc_subject",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identifiant unique renvoyé par le provider OIDC (claim 'sub').",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Admin"), ("READ_ONLY", "Read only")],
                        db_index=True,
                        default="READ_ONLY",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Application user",
                "verbose_name_plural": "Application users",
                "db_table": "app_users",
                "ordering": ["email"],
                "indexes": [
                    models.Index(fields=["email"], name="idx_app_user_email"),
                    models.Index(fields=["role"], name="idx_app_user_role"),
                    models.Index(fields=["is_active"], name="idx_app_user_active"),
                ],
            },
        ),
    ]
