# Generated by Django 5.0.3 on 2026-03-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_appuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appuser",
            old_name="oidc_subject",
            new_name="nni",
        ),
    ]
