sonar.projectKey=biodiv-back
sonar.projectName=Biodiv Backend
sonar.qualitygate.wait=true
sonar.sources=.
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/tests/**,**/venv/**
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/migrations/**,**/tests/**,**/conftest.py,manage.py